# Use a Python base image
FROM python

# Set the working directory inside the container
WORKDIR /app

# Copy the Python application files into the container
COPY . .


# Expose the port that the app will run on
EXPOSE 5000

# Command to run the application
CMD ["python", "bmi.py"]

