version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://database:27017/bank
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database/init.js:/docker-entrypoint-initdb.d/init.js
      - mongo_data:/data/db

volumes:
  mongo_data:
